# Generated by Django 5.2.16 on 2026-07-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSmtpRateLimitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_email_smtp_rate_limit_state',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationIpBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'web_email_verification_ip_blacklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('client_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('was_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'web_email_verification_requests',
            },
        ),
        migrations.AddField(
            model_name='emailverification',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['client_ip', '-created_at'], name='web_ev_ip_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationrequest',
            index=models.Index(fields=['client_ip', '-created_at'], name='web_evr_ip_created_idx'),
        ),
    ]
